version: "3"

services:
  pgdb:
    container_name: pgdb
    # use latest official postgres version
    image: "postgres:alpine"
    env_file:
      # configure postgres
      - ./postgres/database.env
    expose:
      # only avaliable in docker network
      # needed for food_api connection
      - "5432"
    volumes:
      # persist data even if container shuts down
      - auth_data:/var/lib/postgresql/data/
      # run init sql script to create tables
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - net

  auth:
    container_name: auth
    build: .
    image: dv4all/auth:v1.0
    ports:
      - "5433:5433"
    # env_file:
    #   - ./flask-api/food_api.env
    networks:
      - net
    depends_on:
      - pgdb

networks:
  net:

volumes:
  auth_data: